version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: demo-auxodev_local_django
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    image: demo-auxodev_local_celeryworker
    depends_on:
      - redis
      
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: demo-auxodev_local_celerybeat
    depends_on:
      - redis
      
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: demo-auxodev_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
